export const actionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_UNSUCCESS: "SIGN_IN_UNSUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  VALIDATE_TOKEN: "VALIDATE_TOKEN",
  VALIDATE_TOKEN_SUCESS: "VALIDATE_TOKEN_SUCESS",
  VALIDATE_TOKEN_UNSUCCESS: "VALIDATE_TOKEN_UNSUCCESS",
  VALIDATE_TOKEN_FAIL: "VALIDATE_TOKEN_FAIL",
};

export const genericAction = (type, data) => ({
  type,
  payload: data,
});
